;; Gramps key file
;; Automatically created at 2025/03/21 09:25:52

[behavior]
;;addmedia-image-dir=''
;;addmedia-relative-path=0
;;addons-allow-install=0
;;addons-projects=[['Gramps', 'https://raw.githubusercontent.com/gramps-project/addons/master/gramps52', True]]
;;addons-url='https://raw.githubusercontent.com/gramps-project/addons/master/gramps52'
;;autoload=0
;;avg-generation-gap=20
check-for-addon-update-types=['update', 'new']
check-for-addon-updates=4
;;date-about-range=50
;;date-after-range=50
;;date-before-range=50
;;do-not-show-previously-seen-addon-updates=1
;;generation-depth=15
;;immediate-warn=0
last-check-for-addon-updates='2025/03/21'
;;max-age-prob-alive=110
;;max-sib-age-diff=20
;;min-generation-years=13
;;owner-warn=0
;;pop-plugin-status=0
;;previously-seen-addon-updates=[]
;;recent-export-type=3
;;runcheck=0
;;spellcheck=0
;;startup=0
;;surname-guessing=0
translator-needed=0
;;use-tips=0
;;web-search-url='http://google.com/#&q=%(text)s'
;;welcome=100

[colors]
;;border-family=['#cccccc', '#252525']
;;border-family-divorced=['#ff7373', '#720b0b']
;;border-female-alive=['#861f69', '#261111']
;;border-female-dead=['#000000', '#000000']
;;border-male-alive=['#1f4986', '#171d26']
;;border-male-dead=['#000000', '#000000']
;;border-other-alive=['#2a5f16', '#26a269']
;;border-other-dead=['#000000', '#000000']
;;border-unknown-alive=['#8e5801', '#8e5801']
;;border-unknown-dead=['#000000', '#000000']
;;family=['#eeeeee', '#454545']
;;family-civil-union=['#eeeeee', '#454545']
;;family-divorced=['#ffdede', '#5c3636']
;;family-married=['#eeeeee', '#454545']
;;family-unknown=['#eeeeee', '#454545']
;;family-unmarried=['#eeeeee', '#454545']
;;female-alive=['#feccf0', '#62242D']
;;female-dead=['#feccf0', '#3a292b']
;;home-person=['#bbe68a', '#304918']
;;male-alive=['#b8cee6', '#1f344a']
;;male-dead=['#b8cee6', '#2d3039']
;;other-alive=['#94ef9e', '#285b27']
;;other-dead=['#94ef9e', '#062304']
;;scheme=0
;;unknown-alive=['#f3dbb6', '#75507B']
;;unknown-dead=['#f3dbb6', '#35103b']

[csv]
;;delimiter=','
;;dialect='excel'

[database]
;;autobackup=0
;;backend='sqlite'
;;backup-on-exit=1
;;backup-path='/Users/osama'
;;compress-backup=1
;;host=''
;;path='/Users/osama/.local/share/gramps/grampsdb'
;;port=''

[export]
;;proxy-order=[['privacy', 0], ['living', 0], ['person', 0], ['note', 0], ['reference', 0]]

[geography]
;;center-lat=0.0
;;center-lon=0.0
;;lock=0
;;map_service=1
;;path=''
;;personal-map=''
;;show_cross=0
;;use-keypad=1
;;zoom=0
;;zoom_when_center=12

[interface]
;;addonmanager-height=400
;;addonmanager-horiz-position=649
addonmanager-vert-position=449
addonmanager-width=752
dbmanager-height=370
;;dbmanager-horiz-position=17
dbmanager-vert-position=69
dbmanager-width=784
;;dont-ask=0
;;editplaceformat-height=400
;;editplaceformat-horiz-position=726
editplaceformat-vert-position=421
editplaceformat-width=608
;;filter=0
;;fullscreen=0
;;grampletbar-close=0
;;grampspreferences-height=450
;;grampspreferences-horiz-position=674
grampspreferences-vert-position=424
grampspreferences-width=704
;;hide-lds=0
;;ignore-gexiv2=0
;;ignore-osmgpsmap=0
;;ignore-pil=0
;;information-height=400
;;information-horiz-position=109
information-vert-position=50
information-width=608
main-window-height=1254
main-window-horiz-position=0
main-window-vert-position=50
main-window-width=2048
;;mapservice='OpenStreetMap'
;;open-with-default-viewer=0
;;pedview-layout=0
;;pedview-show-images=1
;;pedview-show-marriage=0
;;pedview-show-unknown-people=0
;;pedview-tree-direction=2
;;pedview-tree-size=5
;;person-height=550
;;person-horiz-position=649
person-vert-position=374
person-width=864
;;place-name-height=100
;;place-name-width=450
;;sidebar-text=1
;;size-checked=0
;;statusbar=1
;;surname-box-height=150
;;toolbar-addons=1
;;toolbar-clipboard=1
;;toolbar-on=1
;;toolbar-preference=1
;;toolbar-reports=1
;;toolbar-text=0
;;toolbar-tools=1
;;treemodel-cache-size=1000
;;updateaddons-height=400
;;updateaddons-horiz-position=650
updateaddons-vert-position=421
updateaddons-width=752
;;view=1
;;view-categories=['Dashboard', 'People', 'Relationships', 'Families', 'Ancestry', 'Events', 'Places', 'Geography', 'Sources', 'Citations', 'Repositories', 'Media', 'Notes']

[paths]
;;quick-backup-directory='/Users/osama'
;;quick-backup-filename='%(filename)s_%(year)d-%(month)02d-%(day)02d.%(extension)s'
;;recent-export-dir='/Users/osama'
recent-file='/Users/osama/.local/share/gramps/grampsdb/67dd6740'
;;recent-import-dir='/Users/osama'
;;report-directory='/Users/osama'
;;website-cal-uri=''
;;website-cms-uri=''
;;website-directory='/Users/osama'
;;website-extra-page-name=''
;;website-extra-page-uri=''

[plugin]
;;addonplugins=[]
;;hiddenplugins=[]

[preferences]
;;age-after-death=1
;;age-display-precision=1
;;age-rounded-year=1
;;calendar-format-input=0
;;calendar-format-report=0
;;cite-plugin='cite-legacy'
;;coord-format=0
;;cprefix='C%04d'
date-format=1
;;default-source=0
;;eprefix='E%04d'
family-relation-type=0
;;family-warn=1
;;february-29=0
;;fprefix='F%04d'
;;hide-ep-msg=0
;;invalid-date-format='<b>%s</b>'
;;iprefix='I%04d'
last-view='personview'
last-views=['dashboardview', 'personview', '', '', '', '', '', '', '', '', '', '', '']
;;name-format=1
;;no-given-text='[Missing Given Name]'
;;no-record-text='[Missing Record]'
;;no-surname-text='[Missing Surname]'
;;nprefix='N%04d'
;;online-maps=0
;;oprefix='O%04d'
;;paper-metric=0
;;paper-preference='Letter'
;;patronimic-surname=0
;;place-auto=1
;;place-format=0
;;pprefix='P%04d'
;;private-given-text='[Living]'
;;private-record-text='[Private Record]'
;;private-surname-text='[Living]'
;;quick-backup-include-mode=0
;;rprefix='R%04d'
;;sprefix='S%04d'
;;tag-on-import=0
;;tag-on-import-format='Imported %Y/%m/%d %H:%M:%S'
;;use-last-view=0

[researcher]
;;researcher-addr=''
;;researcher-city=''
;;researcher-country=''
;;researcher-email=''
;;researcher-locality=''
;;researcher-name=''
;;researcher-phone=''
;;researcher-postal=''
;;researcher-state=''

[spacing]
children=[16.954210069444446, 6.781684027777778, 6.781684027777778]
citations=[23.73589409722222, 10.172526041666666, 10.172526041666666, 13.563368055555555]
dbman=[16.954210069444446, 4.2724609375, 7.188585069444445]
events=[6.781684027777778, 10.172526041666666, 6.781684027777778, 6.781684027777778, 27.12673611111111, 13.563368055555555]
person_editor_addresses=[2, 2, 10.172526041666666, 15.2587890625, 6.781684027777778, 6.781684027777778, 6.781684027777778, 5.086263020833333, 5.086263020833333]
person_editor_associations=[2, 2, 16.954210069444446, 6.781684027777778]
person_editor_attributes=[2, 2, 16.954210069444446]
person_editor_citations=[2, 23.73589409722222, 13.563368055555555, 6.781684027777778, 12.20703125, 13.563368055555555, 5.425347222222222]
person_editor_events=[8.138020833333334, 16.276041666666668, 10.172526041666666, 16.276041666666668, 16.276041666666668, 2, 2, 5.425347222222222, 4.069010416666667]
person_editor_internet=[2, 6.781684027777778, 13.563368055555555]
person_editor_ldsord=[2, 2, 10.172526041666666, 10.172526041666666, 5.086263020833333, 13.563368055555555]
person_editor_names=[16.954210069444446, 2, 2, 6.781684027777778, 6.781684027777778]
person_editor_notes=[2, 6.781684027777778]
person_editor_references=[6.781684027777778, 5.086263020833333]
person_editor_surnames=[2, 2, 2, 2]
persontreeview=[16.954210069444446, 5.086263020833333, 5.086263020833333, 6.781684027777778]

[utf8]
;;baptism-symbol='~'
;;birth-symbol='*'
;;buried-symbol='[]'
;;cremated-symbol='⚱'
;;dead-symbol='✝'
;;death-symbol=2
;;divorce-symbol='o|o'
;;engaged-symbol='o'
;;in-use=0
;;killed-symbol='x'
;;marriage-symbol='oo'
;;partner-symbol='o-o'
;;selected-font=''

