;; Gramplet bar configuration file
;; Automatically created at 2025/03/21 09:25:52

[Bar Options]
visible=True
page=0

[Person Filter]
name=Person Filter
height=200
expand=False
detached_width=400
detached_height=300
state=maximized
help_url=Gramps_5.2_Wiki_Manual_-_Gramplets#Gramplet_List
navtypes=['Person']
page=0

